# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
add_newline = false

format = """
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
${custom.iterm_prompt_mark}$character"""

right_format = """
$cmd_duration\
$status"""

[hostname]
disabled = false
format = "[\\[\uF179 $hostname\\]](bold $style)"
#style = "#dfad81"
style = "#ff7d00"
ssh_only = false

[directory]
disabled = false
format = "[$path]($style) "
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = ""

[cmd_duration]
disabled = false
# æ ¼å¼åŒ–: [â³ æŒç»­æ—¶é—´] åè·Ÿä¸€ä¸ªç©ºæ ¼
format = "\\[â€¢ $duration\\]"
# ä»…å½“å‘½ä»¤æ‰§è¡Œæ—¶é—´è¶…è¿‡ 500 æ¯«ç§’æ—¶æ‰æ˜¾ç¤º
min_time = 500
# æ ·å¼: è®¾ç½®ä¸ºåŠ ç²—é»„è‰²
style = "bold yellow"

[status]
# æ ¼å¼åŒ–: [çŠ¶æ€ç  âœ˜] âœ”
format = "[\\[$status âœ˜\\]]($style)"
# æ ·å¼: è®¾ç½®ä¸ºåŠ ç²—çº¢è‰²
style = "bold red"
# disabled = false ç¡®ä¿å®ƒè¢«å¯ç”¨ (é»˜è®¤åªåœ¨å‘½ä»¤å¤±è´¥æ—¶æ˜¾ç¤ºï¼Œè¿™æ­£æ˜¯æˆ‘ä»¬æƒ³è¦çš„)
disabled = false

[kubernetes]
disabled = false
format = '[\[$symbol$context(\($namespace\))\]]($style) '
style = 'cyan bold'

[character]
# å‘½ä»¤æˆåŠŸæ—¶çš„ç¬¦å·
success_symbol = "[â¯](bold green)"
# å‘½ä»¤å¤±è´¥æ—¶çš„ç¬¦å·
error_symbol = "[â¯](bold red)"

[aws]
disabled = true

[time]
disabled = true
format = 'ğŸ•™ [\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '+8'
# time_range = '10:00:00-14:00:00'

[battery]
disabled = true
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '
[[battery.display]]
threshold = 50
style = 'bold yellow'
discharging_symbol = 'ğŸ’¦ '
[[battery.display]]
threshold = 20
style = 'bold red'

[custom.iterm_prompt_mark]
when = '[ "$TERM_PROGRAM" = "iTerm.app" ]'
format = "\u001b\\]133;A\u0007"
shell = "sh"
disabled = false
